name: Generate Snake

on:
  # Schedule the job to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # Allows the workflow to be triggered manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Generate the snake animation
      - uses: Platane/snk@v2
        with:
          github_user_name: frkudn  # Replace with your GitHub username
          outputs: dist/snake.svg

      # Push the generated snake.svg to the output branch
      - name: Push Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
